mexcuda Mex_cuPCG.cpp cuda_pcg.cu ...
    MxArray.cpp ...
    -I./ ...
    -I/usr/local/include  ...
    -I/usr/local/cuda/include ...
    -L/usr/local/lib ...
    -L/usr/local/cuda/lib64 ...
    -lopencv_imgproc  ...
    -lopencv_core  ...
    -lopencv_video  ...
    -lopencv_calib3d  ...
    -lopencv_features2d  ...
    -lopencv_flann  ...
    -lopencv_objdetect ...
    -lopencv_ml  ...
    -lopencv_highgui  ...
    -lopencv_videoio  ...
    -lopencv_imgcodecs  ...
    -lopencv_photo ...
    -lcublas ...
    -lcusparse ...
    -lcudart
